### ISSUE TITLE
A lot of RAM taken by rtmidi2

### ISSUE THREAD

**Issue by freerig** [gesellkammer/rtmidi2#9]
Here is the code I have:
```py
from rtmidi2 import MidiIn
midi_in = MidiIn()
midi_in.open_port(0)

while True:
  message = midi_in.get_message()
  if message:
    print(message)
```
When I run this code, I see in the task manager that python is taking more and more Ram memory. First 100 megabytes, then 500, then 1 GB, then 4 GB, so i can't run the program for long.
![image](https://github.com/gesellkammer/rtmidi2/assets/98414804/43a7d6eb-2843-4e4b-97df-d46b700a4d89)

When I remove the "midi_in.get_message()" line, there is no problem, even if I keep the "while True:"

I don't know if its a rtmidi problem, or a rtmidi2 problem, because I couldn't get rtmidi to work, so I tried rtmidi2.

I use VSCode, with Python 3.11.2 and rtmidi 1.1.2

Thanks

**Comment by gesellkammer** [comment]
Thanks for the report. I will take a look at it and report back here

**Comment by gesellkammer** [comment]
There are two problems here: 

1) the first is the memory problem. This seems to be fixed in the version I just pushed (do pip install -U rtmidi2 and check that the version installed is >= 1.2.0)
2) The so called "blocking" interface you are using via `get_message` returns immediately, returning None if the queue is empty and the message otherwise. Without any sleeping, the loop as you posted will result in 100% CPU usage.

**Comment by freerig** [comment]
Ok, thanks for the fast reply and update. Works fine for me.
